name: Build_Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build_test:
    runs-on: ubuntu-latest
    name: build_test
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Dependencies
        run: npm ci
      - name: Build Code
        run: npm build --if-present
      - name: Test Code
        run: npm test
